{% set version = '0.2-3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lwgeom
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lwgeom_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lwgeom/lwgeom_{{ version }}.tar.gz
  sha256: d628079ee305c1e06072de65c9d9d04d25681735c1e0379103aa435c1f2d087f

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-sf >=0.9_0
    - r-units
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-sf >=0.9_0
    - r-units

test:
  commands:
    - $R -e "library('lwgeom')"           # [not win]
    - "\"%R%\" -e \"library('lwgeom')\""  # [win]

about:
  home: https://github.com/r-spatial/lwgeom/
  license: GPL-2-only
  summary: Access to selected functions found in 'liblwgeom' <https://github.com/postgis/postgis/tree/master/liblwgeom>,
    the light-weight geometry library used by 'PostGIS' <http://postgis.net/>.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - agcopenhaver
    - conda-forge/r

# Package: lwgeom
# Version: 0.2-3
# Title: Bindings to Selected 'liblwgeom' Functions for Simple Features
# Description: Access to selected functions found in 'liblwgeom' <https://github.com/postgis/postgis/tree/master/liblwgeom>, the light-weight geometry library used by 'PostGIS' <http://postgis.net/>.
# Authors@R: c(person("Edzer", "Pebesma", role = c("aut", "cre"), email = "edzer.pebesma@uni-muenster.de", comment = c(ORCID = "0000-0001-8049-7069")), person("Colin", "Rundel", role = "ctb"), person("Andy", "Teucher", role = "ctb"), person("liblwgeom developers", role = "cph"))
# Depends: R (>= 3.3.0)
# Imports: Rcpp, units, sf (>= 0.9-0)
# Suggests: covr, sp, geosphere, testthat
# LinkingTo: Rcpp, sf (>= 0.6-0)
# SystemRequirements: GEOS (>= 3.5.0), PROJ (>= 4.8.0)
# License: GPL-2
# Copyright: file COPYRIGHTS
# URL: https://github.com/r-spatial/lwgeom/
# BugReports: https://github.com/r-spatial/lwgeom/issues/
# Collate: init.R RcppExports.R geohash.R split.R subdivide.R valid.R transform.R bounding_circle.R bearing.R snap_to_grid.R startpoint.R twkb.R perimeter.R clockwise.R geod.R wkt.R
# RoxygenNote: 7.1.0
# NeedsCompilation: yes
# Packaged: 2020-04-12 08:49:57 UTC; edzer
# Author: Edzer Pebesma [aut, cre] (<https://orcid.org/0000-0001-8049-7069>), Colin Rundel [ctb], Andy Teucher [ctb], liblwgeom developers [cph]
# Maintainer: Edzer Pebesma <edzer.pebesma@uni-muenster.de>
# Repository: CRAN
# Date/Publication: 2020-04-12 09:50:02 UTC
