{% set version = "0.2-14" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-lwgeom
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lwgeom_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lwgeom/lwgeom_{{ version }}.tar.gz
  sha256: 26db6cf7dbc8cf43a70e5e2a34941a1c4b65e182f86f58d64ff9f614b3be929c

build:
  number: 5
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-sf                         # [build_platform != target_platform]
    - r-units                      # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-sf >=1.0_15
    - r-units
    - geos
    - proj
  run:
    - r-base
    - r-rcpp
    - r-sf >=1.0_15
    - r-units

test:
  commands:
    - $R -e "library('lwgeom')"           # [not win]
    - "\"%R%\" -e \"library('lwgeom')\""  # [win]

about:
  home: https://r-spatial.github.io/lwgeom/
  dev_url: https://github.com/r-spatial/lwgeom/
  doc_url: https://cran.r-project.org/web/packages/lwgeom/lwgeom.pdf
  license: GPL-2.0-only
  summary: Access to selected functions found in 'liblwgeom' <https://github.com/postgis/postgis/tree/svn-trunk/liblwgeom>, the light-weight geometry library used by 'PostGIS' <http://postgis.net/>.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
  description: Access to selected functions found in liblwgeom, the light-weight geometry library used by PostGIS
extra:
  recipe-maintainers:
    - agcopenhaver
    - conda-forge/r
